FROM node:18-alpine

# WORKDIR /usr/src/app
# 
# RUN corepack enable \
#     && corepack prepare pnpm@latest --activate
# 
# COPY package.json pnpm-lock.yaml ./
# 
# COPY package.json package-lock.json* pnpm-lock.yaml* ./
# 
# RUN pnpm install --frozen-lockfile
# 
# RUN pnpm build
# COPY . . # ine files
# 
# EXPOSE 3000 # nebude treba
# 
# CMD [true]