services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Táto hodnota sa načíta z .env súboru (načítaného docker-compose)
        # alebo z prostredia shellu, ak .env súbor túto premennú nedefinuje.
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    ports:
      - "3000:3000" # Mapuje port 3000 na hostiteľovi na port 3000 v kontajneri (kde Nginx počúva)
    env_file:
      - .env
    restart: unless-stopped

#  tests:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    env_file:
#      - .env
#    volumes:
#      - ./backend:/usr/src/app
#    working_dir: /usr/src/app
#    environment:
#      PYTHONPATH: /usr/src/app
#    entrypoint: []
#    command: ["pytest", "-q"]

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
