services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  tests:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - PYTHONPATH=/usr/src/app
    command: ["pytest", "-q"]

volumes:
  pgdata:

